export enum ActionsTypes {
  GET_POKEMONS = "GET_POKEMONS",
  GET_POKEMON_DATA = "GET_POKEMON_DATA",
  GET_SINGLE_POKEMON = "GET_SINGLE_POKEMON",
  SET_FAVORITE = "SET_FAVORITE",
  SET_FILTER = "SET_FILTER",
  SET_QUERY = "SET_QUERY",
}
